version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    ports:
      - "8095:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # âœ… Add queue worker service
  queue-worker:
    user: "www-data"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: >
      bash -c "
        php artisan config:clear &&
        php artisan cache:clear &&
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1 &
        php artisan queue:work --tries=3 --timeout=120 --sleep=1
      "
    volumes:
      - ./:/var/www
    depends_on:
      - db
    restart: always   # always restart queue workers

  db:
    image: mysql:8
    environment:
      - TZ=Asia/Kolkata
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nse_stock
      - MYSQL_USER=stock_admin
      - MYSQL_PASSWORD=admin_stock
    ports:
      - "3395:3306"
    command: --default-time-zone="+05:30"
